apiVersion: apps/v1
kind: Deployment
metadata:
  name: typespeed-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typespeed-app
  template:
    metadata:
      labels:
        app: typespeed-app
    spec:
      containers:
        - name: typespeed-container
          image: anirudh06/loon:latest
          ports:
            - containerPort: 8501